### ISSUE TITLE
Python3 and makefile fixes

### ISSUE THREAD

**Issue by berndporr** [EduardoSebastianRodriguez/REAL-TIME-FIR-FILTER-PYTHON#1]
[REAL-TIME-FIR-FILTER-PYTHON.zip](https://github.com/EduardoSebastianRodriguez/REAL-TIME-FIR-FILTER-PYTHON/files/1565154/REAL-TIME-FIR-FILTER-PYTHON.zip)
Please remove the binaries from the repo and I've attached a zip which has a makefile instead of the txt file to compile it. The demo loads the .so from the parent dir so that it can be kept in one place and not 3.
Please fix in your code.

**Comment by EduardoSebastianRodriguez** [comment]
Lots of thanks!!! I didn't realized I have this comment until few minutes ago... I am applying the changes and fixing the problems. Again, ... lots of thanks and sorry for the delay :)

**Comment by berndporr** [comment]
No worries!
