### ISSUE TITLE
"_FIR.so" file was missing

### ISSUE THREAD

**Issue by Cly1st** [EduardoSebastianRodriguez/REAL-TIME-FIR-FILTER-PYTHON#2]
I cannot found an "_FIR.so" file in the BASE folder.
Can you kindly upload it?

**Comment by john2zy** [comment]
You need to compile it with make and swig yourself. But anyway, I compiled it for you.

Edit: I used python3.6 but it gives undefined symbol error when importing it. So you might want to use python3.5.

[_FIR.zip](https://github.com/EduardoSebastianRodriguez/REAL-TIME-FIR-FILTER-PYTHON/files/4632842/_FIR.zip)
